version: '3.9'

services:
  php:
    build: php
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./php/php7:/etc/php7
      - ./php/www/conf:/var/www/conf:ro
      - ./php/www/html:/var/www/html
      - ./php/services.d:/etc/services.d:ro

  ssh:
    build: ssh
    restart: always
    ports:
      - "22:22"
    volumes:
      - ./ssh/conf/sshd_config:/etc/ssh/sshd_config:ro
      - ./ssh/services.d:/etc/services.d:ro

  php-sqli:
    build: AlternativePHP_BaseImage/PHP
    restart: always
    ports:
      - "8080:80"
    links:
      - "db-sqli:database"

  db-sqli:
    build: AlternativePHP_BaseImage/SQL
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=cueh
      - MYSQL_DATABASE=maindb