version: '3.9'

services:
  php:
    build: php
    restart: always
    ports:
      - "80:80"

  ssh:
    build: ssh
    restart: always
    ports:
      - "22:22"

  php-sqli:
    build: AlternativePHP_BaseImage/PHP
    restart: always
    ports:
      - "8080:80"
    links:
      - "db-sqli:database"

  db-sqli:
    build: AlternativePHP_BaseImage/SQL
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=cueh
      - MYSQL_DATABASE=maindb